name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  server-test:
    strategy:
      matrix:
        etcd: ['quay.io/coreos/etcd:latest']
        go: ['1.17', '1.16' , '1.18']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    services:
      etcd:
        image: ${{ matrix.etcd }}
        ports:
          - 2379:2379
          - 2380:2380
        env:
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: go mod package cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('tests/go.mod') }}

      - name: Test
        run: |
          make test
